spring:
  profiles:
    active:
      - dev

---
service:
  port: 8001
spring:
    profiles: dev
    application:
       name: microservice-config-dept-client
    datasource:
    type: com.alibaba.druid.pool.DruidDataSource   
    driver-class-name: org.gjt.mm.mysql.Driver  
    url: jdbc:mysql://localhost:3306/clouddb01
    username: root
    password: root
    dbcp2:
      min-idle: 5             
      initial-size: 5         
      max-total: 5           
      max-wait-millis: 200  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml   
  type-aliases-package: com.atguigu.springcloud.entities 
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml 

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true 

info:
  app.name: atguigu-microcloudservice-springcloudconfig01
  company.name: www.atguigu.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}

---
service:
  port: 8001
spring:
    profiles: test
    application:
       name: microservice-config-dept-client
    datasource:
    type: com.alibaba.druid.pool.DruidDataSource   
    driver-class-name: org.gjt.mm.mysql.Driver  
    url: jdbc:mysql://localhost:3306/clouddb02
    username: root
    password: root
    dbcp2:
      min-idle: 5             
      initial-size: 5         
      max-total: 5           
      max-wait-millis: 200  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml   
  type-aliases-package: com.atguigu.springcloud.entities 
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml 

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true 

info:
  app.name: atguigu-microcloudservice-springcloudconfig01
  company.name: www.atguigu.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}